version: "3"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.49.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:2.9.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.0.0
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # grants admin role to anonymous access
      - GF_AUTH_ANONYMOUS_ENABLED=true # removes login 1/2
      - GF_AUTH_BASIC_ENABLED=false # removes login 2/2
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Cognito
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=72btnvjii5f272agv6h0vvjft9
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=18sbm8ujf1fl322gsi12el4tbrahd6ss508rkb2pav8b80majbdu
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid email profile
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://grafana-test-0617.auth.ap-northeast-1.amazoncognito.com/oauth2/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://grafana-test-0617.auth.ap-northeast-1.amazoncognito.com/oauth2/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://grafana-test-0617.auth.ap-northeast-1.amazoncognito.com/oauth2/userInfo
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  app:
    build: ./app
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    ports:
      - 8082:80
    networks:
      - grafana
